### ISSUE TITLE
how to avoid filter_sitemap_item for external page ( provider.php )

### ISSUE THREAD

**Issue by belladonnaf** [OddOneOut/bwp-google-xml-sitemaps#41]
hello. 

external page is intented for external url, so it should be avoid "filter_sitemap_item"
( /bwp-google-xml-sitemaps/src/sitemap/provider/provider.php )

usually, external page must be not working this version. 

but i have solution.

provider.php <--

	public function get_items()
	{
		if( $this->module->requested == 'external' ){
			return	$this->module->get_data();
		} else {
			return array_values(
				array_filter(
					$this->module->get_data(),
					array($this, 'filter_sitemap_item')
				)
			);
		}
	}

i hope version upgrade include my source.

**Comment by kminh** [comment]
External pages here are external to WordPress, i.e. pages that are not generated by WordPress. Following the [XML sitemap protocol](https://www.sitemaps.org/protocol.html#location), I don't think you can put URLs linking to external websites in your sitemaps.

Please let me know if you would like to reopen this issue.
