### ISSUE TITLE
one sitemap index with all sites instead of incorrect current one website index

### ISSUE THREAD

**Issue by nekromoff** [OddOneOut/bwp-google-xml-sitemaps#46]
Currently, BWP generates sitemap indexes separately for each website in the network (subfolder install). This is incorrect approach.

There should be one master sitemap index with all websites in the root folder and this should have individual network sites linked.

**Comment by kminh** [comment]
> Currently, BWP generates sitemap indexes separately for each website in the network (subfolder install). This is incorrect approach.
Could you please advise why this is the incorrect approach?

Currently, BWP Sitemaps provides a `site.xml` sitemap that lists all the blogs within a network, as shown below:
![screenshot from 2017-11-10 23-03-28](https://user-images.githubusercontent.com/6402124/32666998-ed0d5c6a-c66b-11e7-9cdb-819b6d380012.png)

**Comment by nekromoff** [comment]
OK, then I must have missed that option, which is exactly what my point was.
