### ISSUE TITLE
plugin not generating posts.xml etc. into the sitemap index.

### ISSUE THREAD

**Issue by nekromoff** [OddOneOut/bwp-google-xml-sitemaps#9]
Only:
/site.xml
/taxonomy_post_tag.xml
are added to the sitemapindex, but no posts.xml, pages.xml etc. for a blog, where all of these are enabled (i.e. not disabled) - basic setup options are kept.

**Comment by tpberntsen** [comment]
I was having the same problems with my WordPress instance - and not just with this particular sitemap plugin. 

I had WP Super Cache running and suspected it to be the culprit. Disabled the caching plugin, then deactivated and reactivated the sitemap plugin, and lo and behold: sitemap indexing bliss.

**Comment by kminh** [comment]
Archived because not reproducible. Please feel free to reopen if required.
